# Site settings
author: Olivia
title: Learning Through Doing
header-img: img/home-bg.png
email: olivialonyc@gmail.com
copyright_name: Olivia
description: > # this means to ignore newlines until "baseurl:"
  Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  olivialonyc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
